<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hitung</name>
   <tag></tag>
   <elementGuidId>9566eef5-f84e-483d-93b2-4da650cf94eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-main.px-5.d-block.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>849aa1c5-1484-4f83-bc28-130b9cef7a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c8c134ca-4566-4352-b3b9-7f407808614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-main px-5 d-block w-100</value>
      <webElementGuid>d2fad1d0-41de-464a-94e5-fc1c635939e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung</value>
      <webElementGuid>784e44b4-33e1-418b-ba5f-07bfd3150479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung_harga_button&quot;)/button[@class=&quot;btn btn-main px-5 d-block w-100&quot;]</value>
      <webElementGuid>b7102d43-234f-4abf-8fbe-eb25497b17ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>9c66d821-989c-4964-9571-1adf181245d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hitung_harga_button']/button</value>
      <webElementGuid>60433a3c-3063-4618-873f-fc0aad6d574e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>b4efa80f-352d-4235-a152-ed474ca47d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Hitung' or . = 'Hitung')]</value>
      <webElementGuid>21aff1ec-6184-469e-b534-2acb35314667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
